package com.span.ashless.data.local

import androidx.room.ConstructedBy
import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.RoomDatabaseConstructor

@Database(entities = [CigaretteEntryEntity::class, ProgramEntity::class], version = 2, exportSchema = false)
@ConstructedBy(AshlessDatabaseConstructor::class)
abstract class AshlessDatabase : RoomDatabase() {
    abstract fun entryDao(): CigaretteEntryDao
    abstract fun programDao(): ProgramDao
}

// Actual is generated by Room's KSP processor.
@Suppress("NO_ACTUAL_FOR_EXPECT")
expect object AshlessDatabaseConstructor : RoomDatabaseConstructor<AshlessDatabase> {
    override fun initialize(): AshlessDatabase
}
